### ISSUE TITLE
ModelTES needs to be able to compute piled-up pulses

### ISSUE THREAD

**Issue by joefowler** [ggggggggg/ModelTES.jl#7]
At some version in the past, one could use ModelTES to compute the temperature and current when there was more than one pulse, but either I am totally unable to find it, or the current API does not allow for multiple piled-up pulses. It needs to do so.

**Comment by ggggggggg** [comment]
Resolved by https://github.com/ggggggggg/ModelTES.jl/commit/7cff75b9e761f7b63c047870d886f368b9069050

**Comment by joefowler** [comment]
Fixed in 7cff75b
